[tool.poetry]
name = "lockstock"
version = "0.1.0"
description = ""
authors = ["yagodkin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.20.0.post0"
openai = "^1.82.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
